/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFirstCalculator;

/**
 *
 * @author a7med
 */
public class Programmer extends javax.swing.JFrame {

    int FirstNum;
    int SecondNum;
    int Result;
    String Operation;
    
    public Programmer() {
        setSize(735,445);
        initComponents();
    }
    private void DecEquation(){
        int Dec = Integer.parseInt(Display.getText());
        DecDisplay.setText(String.valueOf(Dec));
        
        String HexNumber = Display.getText();
        HexDisplay.setText((Integer.toHexString(Dec)).toUpperCase());
        
        String Bin = Integer.toBinaryString(Integer.parseInt(HexNumber));
        BinDisplay.setText(Bin);

        String Oct = Integer.toOctalString(Integer.parseInt(HexNumber));
        OctDisplay.setText(Oct);
    }
    private void HexEquation(){
        String HexNumber=Display.getText();
        HexDisplay.setText(String.valueOf(HexNumber));
        
        String Dec=String.valueOf(Integer.parseInt(HexNumber,16));
        DecDisplay.setText(Dec);
        
        String Bin = Integer.toBinaryString(Integer.parseInt(Dec));
        BinDisplay.setText(Bin);
        
        String Oct = Integer.toOctalString(Integer.parseInt(Dec));
        OctDisplay.setText(Oct);
    }
    private void OctEquation(){
        String Oct = Display.getText();
        OctDisplay.setText(Oct);
        
        int Dec=Integer.parseInt(Oct,8); 
        DecDisplay.setText(String.valueOf(Dec));
        
        String Hex = Integer.toHexString(Integer.parseInt(Oct, 8));
        HexDisplay.setText(Hex);
        
        String Bin = Integer.toBinaryString(Dec);
        BinDisplay.setText(Bin);
    }
    private void BinEquation(){
        String Bin = Display.getText();
        BinDisplay.setText(Bin);
        
        int Dec = Integer.parseInt(Bin,2);
        DecDisplay.setText(String.valueOf(Dec));
        
        String HexNumber = Display.getText();
        HexDisplay.setText((Integer.toHexString(Dec)).toUpperCase());
        
        String Oct = Integer.toOctalString(Dec);
        OctDisplay.setText(Oct);
    }
    private void TurnOffABC(){
        ButtonA.setEnabled(false);
        ButtonB.setEnabled(false);
        ButtonC.setEnabled(false);
        ButtonD.setEnabled(false);
        ButtonE.setEnabled(false);
        ButtonF.setEnabled(false);
    }
    private void TurnOffNo8To9(){
        ButtonNo8.setEnabled(false);
        ButtonNo9.setEnabled(false);
    }
    private void TurnOffNo2To9(){
        ButtonNo2.setEnabled(false);
        ButtonNo3.setEnabled(false);
        ButtonNo4.setEnabled(false);
        ButtonNo5.setEnabled(false);
        ButtonNo6.setEnabled(false);
        ButtonNo7.setEnabled(false);
        ButtonNo8.setEnabled(false);
        ButtonNo9.setEnabled(false);
    }
    private void TurnOnABC(){
        ButtonA.setEnabled(true);
        ButtonB.setEnabled(true);
        ButtonC.setEnabled(true);
        ButtonD.setEnabled(true);
        ButtonE.setEnabled(true);
        ButtonF.setEnabled(true);
    }
    private void TurnOnNo2To9(){
        ButtonNo2.setEnabled(true);
        ButtonNo3.setEnabled(true);
        ButtonNo4.setEnabled(true);
        ButtonNo5.setEnabled(true);
        ButtonNo6.setEnabled(true);
        ButtonNo7.setEnabled(true);
        ButtonNo8.setEnabled(true);
        ButtonNo9.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        Display = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();
        ButtonNo9 = new javax.swing.JButton();
        ButtonNo7 = new javax.swing.JButton();
        ButtonNo8 = new javax.swing.JButton();
        ButtonPercentage = new javax.swing.JButton();
        ButtonNo5 = new javax.swing.JButton();
        ButtonNo3 = new javax.swing.JButton();
        ButtonNo1 = new javax.swing.JButton();
        ButtonNo2 = new javax.swing.JButton();
        ButtonNo4 = new javax.swing.JButton();
        ButtonNo6 = new javax.swing.JButton();
        ButtonBackspace = new javax.swing.JButton();
        ButtonPlusMinus = new javax.swing.JButton();
        ButtonNo0 = new javax.swing.JButton();
        ButtonMultiplicatioin = new javax.swing.JButton();
        ButtonDIvision = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        ButtonDec = new javax.swing.JButton();
        ButtonBin = new javax.swing.JButton();
        ButtonAnd = new javax.swing.JButton();
        ButtonNAnd = new javax.swing.JButton();
        ButtonNOr = new javax.swing.JButton();
        ButtonNot = new javax.swing.JButton();
        ButtonHex = new javax.swing.JButton();
        ButtonXOr = new javax.swing.JButton();
        ButtonOct = new javax.swing.JButton();
        ButtonOr = new javax.swing.JButton();
        ButtonA = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        ButtonF = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        BinDisplay = new javax.swing.JTextField();
        HexDisplay = new javax.swing.JTextField();
        DecDisplay = new javax.swing.JTextField();
        OctDisplay = new javax.swing.JTextField();
        ButtonFromDec = new javax.swing.JRadioButton();
        ButtonFromHex = new javax.swing.JRadioButton();
        ButtonFromBin = new javax.swing.JRadioButton();
        ButtonFromOct = new javax.swing.JRadioButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        TitleLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(232, 155, 25));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Programmer Calculator");
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(50, 0, 620, 47);

        BackButton.setBackground(new java.awt.Color(95, 64, 59));
        BackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(201, 176, 168));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(10, 10, 73, 30);

        Display.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(Display);
        Display.setBounds(10, 50, 720, 82);

        ButtonReset.setBackground(new java.awt.Color(29, 76, 170));
        ButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        ButtonReset.setText("C");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonReset);
        ButtonReset.setBounds(100, 140, 70, 60);

        ButtonNo9.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo9.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo9.setText("9");
        ButtonNo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo9ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo9);
        ButtonNo9.setBounds(180, 200, 70, 60);

        ButtonNo7.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo7.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo7.setText("7");
        ButtonNo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo7);
        ButtonNo7.setBounds(20, 200, 70, 60);

        ButtonNo8.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo8.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo8.setText("8");
        ButtonNo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo8);
        ButtonNo8.setBounds(100, 200, 70, 60);

        ButtonPercentage.setBackground(new java.awt.Color(29, 76, 170));
        ButtonPercentage.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPercentage.setText("%");
        getContentPane().add(ButtonPercentage);
        ButtonPercentage.setBounds(180, 140, 70, 60);

        ButtonNo5.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo5.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo5.setText("5");
        ButtonNo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo5);
        ButtonNo5.setBounds(100, 260, 70, 60);

        ButtonNo3.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo3.setText("3");
        ButtonNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo3);
        ButtonNo3.setBounds(180, 320, 70, 60);

        ButtonNo1.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo1.setText("1");
        ButtonNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo1);
        ButtonNo1.setBounds(20, 320, 70, 60);

        ButtonNo2.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo2.setText("2");
        ButtonNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo2);
        ButtonNo2.setBounds(100, 320, 70, 60);

        ButtonNo4.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo4.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo4.setText("4");
        ButtonNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo4);
        ButtonNo4.setBounds(20, 260, 70, 60);

        ButtonNo6.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo6.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo6.setText("6");
        ButtonNo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo6);
        ButtonNo6.setBounds(180, 260, 70, 60);

        ButtonBackspace.setBackground(new java.awt.Color(29, 76, 170));
        ButtonBackspace.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBackspace.setText("←");
        ButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBackspace);
        ButtonBackspace.setBounds(20, 140, 70, 60);

        ButtonPlusMinus.setBackground(new java.awt.Color(29, 76, 170));
        ButtonPlusMinus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPlusMinus.setText("+/-");
        ButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlusMinus);
        ButtonPlusMinus.setBounds(20, 380, 70, 60);

        ButtonNo0.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo0.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo0.setText("0");
        ButtonNo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo0ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo0);
        ButtonNo0.setBounds(100, 380, 70, 60);

        ButtonMultiplicatioin.setBackground(new java.awt.Color(29, 76, 170));
        ButtonMultiplicatioin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMultiplicatioin.setText("×");
        ButtonMultiplicatioin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicatioinActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMultiplicatioin);
        ButtonMultiplicatioin.setBounds(260, 200, 70, 60);

        ButtonDIvision.setBackground(new java.awt.Color(29, 76, 170));
        ButtonDIvision.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDIvision.setText("÷");
        ButtonDIvision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDIvisionActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDIvision);
        ButtonDIvision.setBounds(260, 140, 70, 60);

        ButtonPlus.setBackground(new java.awt.Color(29, 76, 170));
        ButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPlus.setText("+");
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlus);
        ButtonPlus.setBounds(260, 320, 70, 60);

        ButtonMinus.setBackground(new java.awt.Color(29, 76, 170));
        ButtonMinus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMinus);
        ButtonMinus.setBounds(260, 260, 70, 60);

        ButtonEqual.setBackground(new java.awt.Color(29, 76, 170));
        ButtonEqual.setForeground(new java.awt.Color(153, 153, 153));
        ButtonEqual.setText("=");
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEqual);
        ButtonEqual.setBounds(180, 380, 70, 60);

        ButtonDec.setBackground(new java.awt.Color(167, 86, 0));
        ButtonDec.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDec.setText("DEC");
        ButtonDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDec);
        ButtonDec.setBounds(500, 200, 70, 60);

        ButtonBin.setBackground(new java.awt.Color(167, 86, 0));
        ButtonBin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBin.setText("BIN");
        ButtonBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBinActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBin);
        ButtonBin.setBounds(500, 320, 70, 60);

        ButtonAnd.setBackground(new java.awt.Color(29, 172, 170));
        ButtonAnd.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAnd.setText("AND");
        ButtonAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAndActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAnd);
        ButtonAnd.setBounds(340, 140, 70, 60);

        ButtonNAnd.setBackground(new java.awt.Color(29, 172, 170));
        ButtonNAnd.setForeground(new java.awt.Color(0, 0, 0));
        ButtonNAnd.setText("NAND");
        ButtonNAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNAndActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNAnd);
        ButtonNAnd.setBounds(340, 380, 70, 60);

        ButtonNOr.setBackground(new java.awt.Color(29, 172, 170));
        ButtonNOr.setForeground(new java.awt.Color(0, 0, 0));
        ButtonNOr.setText("NOR");
        ButtonNOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNOrActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNOr);
        ButtonNOr.setBounds(260, 380, 70, 60);

        ButtonNot.setBackground(new java.awt.Color(29, 172, 170));
        ButtonNot.setForeground(new java.awt.Color(0, 0, 0));
        ButtonNot.setText("NOT");
        ButtonNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNotActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNot);
        ButtonNot.setBounds(340, 260, 70, 60);

        ButtonHex.setBackground(new java.awt.Color(167, 86, 0));
        ButtonHex.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHex.setText("HEX");
        ButtonHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHexActionPerformed(evt);
            }
        });
        ButtonHex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ButtonHexKeyTyped(evt);
            }
        });
        getContentPane().add(ButtonHex);
        ButtonHex.setBounds(500, 140, 70, 60);

        ButtonXOr.setBackground(new java.awt.Color(29, 172, 170));
        ButtonXOr.setForeground(new java.awt.Color(0, 0, 0));
        ButtonXOr.setText("XOR");
        ButtonXOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXOrActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonXOr);
        ButtonXOr.setBounds(340, 320, 70, 60);

        ButtonOct.setBackground(new java.awt.Color(167, 86, 0));
        ButtonOct.setForeground(new java.awt.Color(255, 255, 255));
        ButtonOct.setText("OCT");
        ButtonOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOctActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonOct);
        ButtonOct.setBounds(500, 260, 70, 60);

        ButtonOr.setBackground(new java.awt.Color(29, 172, 170));
        ButtonOr.setForeground(new java.awt.Color(0, 0, 0));
        ButtonOr.setText("OR");
        ButtonOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOrActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonOr);
        ButtonOr.setBounds(340, 200, 70, 60);

        ButtonA.setBackground(new java.awt.Color(70, 63, 58));
        ButtonA.setForeground(new java.awt.Color(255, 255, 255));
        ButtonA.setText("A");
        ButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonA);
        ButtonA.setBounds(420, 140, 70, 60);

        ButtonC.setBackground(new java.awt.Color(70, 63, 58));
        ButtonC.setForeground(new java.awt.Color(255, 255, 255));
        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC);
        ButtonC.setBounds(420, 260, 70, 60);

        ButtonB.setBackground(new java.awt.Color(70, 63, 58));
        ButtonB.setForeground(new java.awt.Color(255, 255, 255));
        ButtonB.setText("B");
        ButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonB);
        ButtonB.setBounds(420, 200, 70, 60);

        ButtonF.setBackground(new java.awt.Color(70, 63, 58));
        ButtonF.setForeground(new java.awt.Color(255, 255, 255));
        ButtonF.setText("F");
        ButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonF);
        ButtonF.setBounds(500, 380, 70, 60);

        ButtonD.setBackground(new java.awt.Color(70, 63, 58));
        ButtonD.setForeground(new java.awt.Color(255, 255, 255));
        ButtonD.setText("D");
        ButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonD);
        ButtonD.setBounds(420, 320, 70, 60);

        ButtonE.setBackground(new java.awt.Color(70, 63, 58));
        ButtonE.setForeground(new java.awt.Color(255, 255, 255));
        ButtonE.setText("E");
        ButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE);
        ButtonE.setBounds(420, 380, 70, 60);

        BinDisplay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BinDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(BinDisplay);
        BinDisplay.setBounds(580, 330, 140, 40);

        HexDisplay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        HexDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(HexDisplay);
        HexDisplay.setBounds(580, 150, 140, 40);

        DecDisplay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DecDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(DecDisplay);
        DecDisplay.setBounds(580, 210, 140, 40);

        OctDisplay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OctDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(OctDisplay);
        OctDisplay.setBounds(580, 270, 140, 40);

        ButtonFromDec.setForeground(new java.awt.Color(255, 255, 255));
        ButtonFromDec.setText("DEC");
        ButtonFromDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFromDecActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonFromDec);
        ButtonFromDec.setBounds(650, 380, 60, 28);

        ButtonFromHex.setForeground(new java.awt.Color(255, 255, 255));
        ButtonFromHex.setText("HEX");
        ButtonFromHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFromHexActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonFromHex);
        ButtonFromHex.setBounds(590, 380, 60, 28);

        ButtonFromBin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonFromBin.setText("BIN");
        ButtonFromBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFromBinActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonFromBin);
        ButtonFromBin.setBounds(650, 410, 60, 28);

        ButtonFromOct.setForeground(new java.awt.Color(255, 255, 255));
        ButtonFromOct.setText("OCT");
        ButtonFromOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFromOctActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonFromOct);
        ButtonFromOct.setBounds(590, 410, 60, 28);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFirstCalculator/BlackWoodBackground.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 740, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Start().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setSize(755, 488);
    }//GEN-LAST:event_formWindowActivated

    private void ButtonNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo4ActionPerformed
        String Number = Display.getText() + ButtonNo4.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo4ActionPerformed

    private void ButtonNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo1ActionPerformed
        String Number = Display.getText() + ButtonNo1.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo1ActionPerformed

    private void ButtonNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo2ActionPerformed
        String Number = Display.getText() + ButtonNo2.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo2ActionPerformed

    private void ButtonNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo3ActionPerformed
        String Number = Display.getText() + ButtonNo3.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo3ActionPerformed

    private void ButtonNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo5ActionPerformed
        String Number = Display.getText() + ButtonNo5.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo5ActionPerformed

    private void ButtonNo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo6ActionPerformed
        String Number = Display.getText() + ButtonNo6.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo6ActionPerformed

    private void ButtonNo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo7ActionPerformed
        String Number = Display.getText() + ButtonNo7.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo7ActionPerformed

    private void ButtonNo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo8ActionPerformed
        String Number = Display.getText() + ButtonNo8.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo8ActionPerformed

    private void ButtonNo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo9ActionPerformed
        String Number = Display.getText() + ButtonNo9.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo9ActionPerformed

    private void ButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusMinusActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Number * (-1) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonPlusMinusActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        String Result;
        SecondNum =Integer.parseInt(Display.getText());
        if (Operation == "+"){
            Display.setText(String.valueOf(FirstNum+SecondNum));
        }
        else if (Operation == "-"){
            Display.setText(String.valueOf(FirstNum-SecondNum));
        }
        else if (Operation == "*"){
            Display.setText(String.valueOf(FirstNum*SecondNum));
        }
        else if (Operation == "/"){
            Display.setText(String.valueOf(FirstNum/SecondNum));
        }
        else if (Operation =="&"){
            Display.setText(String.valueOf(FirstNum&SecondNum));
        }
        else if (Operation =="|"){
            Display.setText(String.valueOf(FirstNum|SecondNum));
        }
        else if (Operation =="~"){
            Display.setText(String.valueOf(~FirstNum));
        }
        else if (Operation =="X|"){
            Display.setText(String.valueOf(FirstNum^SecondNum));
        }
        else if (Operation =="!&"){
            Display.setText(String.valueOf(~(FirstNum&SecondNum)));
        }
        else if (Operation =="!|"){
            Display.setText(String.valueOf(~(FirstNum|SecondNum)));
        }
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void ButtonNo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo0ActionPerformed
        String Number = Display.getText() + ButtonNo0.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo0ActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        FirstNum =Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation=("+");
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        FirstNum =Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation=("-");
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonMultiplicatioinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicatioinActionPerformed
        FirstNum =Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation=("*");
    }//GEN-LAST:event_ButtonMultiplicatioinActionPerformed

    private void ButtonDIvisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDIvisionActionPerformed
        FirstNum =Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation=("/");
    }//GEN-LAST:event_ButtonDIvisionActionPerformed

    private void ButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackspaceActionPerformed
        String Backspace = null;
        if (Display.getText().length() > 0){
            StringBuilder strB = new StringBuilder(Display.getText());
            strB.deleteCharAt(Display.getText().length() -1);
            Backspace = strB.toString();
            Display.setText(Backspace);
        }
    }//GEN-LAST:event_ButtonBackspaceActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        Display.setText("");
        HexDisplay.setText("");
        OctDisplay.setText("");
        DecDisplay.setText("");
        BinDisplay.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecActionPerformed
        TurnOffABC();
        TurnOnNo2To9();
    }//GEN-LAST:event_ButtonDecActionPerformed

    private void ButtonBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBinActionPerformed
        TurnOffABC();
        TurnOffNo2To9();
    }//GEN-LAST:event_ButtonBinActionPerformed

    private void ButtonAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAndActionPerformed
        FirstNum=Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation="&";
    }//GEN-LAST:event_ButtonAndActionPerformed

    private void ButtonNAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNAndActionPerformed
        FirstNum=Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation="!&";
    }//GEN-LAST:event_ButtonNAndActionPerformed

    private void ButtonNOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNOrActionPerformed
        FirstNum=Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation="!|";
    }//GEN-LAST:event_ButtonNOrActionPerformed

    private void ButtonNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNotActionPerformed
        FirstNum=Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation="~";
    }//GEN-LAST:event_ButtonNotActionPerformed

    private void ButtonHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHexActionPerformed
        TurnOnABC();
        TurnOnNo2To9();
    }//GEN-LAST:event_ButtonHexActionPerformed

    private void ButtonXOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXOrActionPerformed
        FirstNum=Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation="X|";
    }//GEN-LAST:event_ButtonXOrActionPerformed

    private void ButtonOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOctActionPerformed
        TurnOffABC();
        TurnOffNo8To9();
    }//GEN-LAST:event_ButtonOctActionPerformed

    private void ButtonOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOrActionPerformed
        FirstNum=Integer.parseInt(Display.getText());
        Display.setText(null);
        Operation="|";
    }//GEN-LAST:event_ButtonOrActionPerformed

    private void ButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAActionPerformed
        String Char = Display.getText() + ButtonA.getText();
        Display.setText(Char);
    }//GEN-LAST:event_ButtonAActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        String Char = Display.getText() + ButtonC.getText();
        Display.setText(Char);
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBActionPerformed
        String Char = Display.getText() + ButtonB.getText();
        Display.setText(Char);
    }//GEN-LAST:event_ButtonBActionPerformed

    private void ButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFActionPerformed
        String Char = Display.getText() + ButtonF.getText();
        Display.setText(Char);
    }//GEN-LAST:event_ButtonFActionPerformed

    private void ButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDActionPerformed
        String Char = Display.getText() + ButtonD.getText();
        Display.setText(Char);
    }//GEN-LAST:event_ButtonDActionPerformed

    private void ButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEActionPerformed
        String Char = Display.getText() + ButtonE.getText();
        Display.setText(Char);
    }//GEN-LAST:event_ButtonEActionPerformed

    private void ButtonHexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonHexKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHexKeyTyped

    private void ButtonFromDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFromDecActionPerformed
        DecEquation();
    }//GEN-LAST:event_ButtonFromDecActionPerformed

    private void ButtonFromHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFromHexActionPerformed
        HexEquation();
    }//GEN-LAST:event_ButtonFromHexActionPerformed

    private void ButtonFromOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFromOctActionPerformed
        OctEquation();
    }//GEN-LAST:event_ButtonFromOctActionPerformed

    private void ButtonFromBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFromBinActionPerformed
        BinEquation();
    }//GEN-LAST:event_ButtonFromBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programmer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programmer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programmer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programmer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programmer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField BinDisplay;
    private javax.swing.JButton ButtonA;
    private javax.swing.JButton ButtonAnd;
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonBackspace;
    private javax.swing.JButton ButtonBin;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonDIvision;
    private javax.swing.JButton ButtonDec;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonF;
    private javax.swing.JRadioButton ButtonFromBin;
    private javax.swing.JRadioButton ButtonFromDec;
    private javax.swing.JRadioButton ButtonFromHex;
    private javax.swing.JRadioButton ButtonFromOct;
    private javax.swing.JButton ButtonHex;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonMultiplicatioin;
    private javax.swing.JButton ButtonNAnd;
    private javax.swing.JButton ButtonNOr;
    private javax.swing.JButton ButtonNo0;
    private javax.swing.JButton ButtonNo1;
    private javax.swing.JButton ButtonNo2;
    private javax.swing.JButton ButtonNo3;
    private javax.swing.JButton ButtonNo4;
    private javax.swing.JButton ButtonNo5;
    private javax.swing.JButton ButtonNo6;
    private javax.swing.JButton ButtonNo7;
    private javax.swing.JButton ButtonNo8;
    private javax.swing.JButton ButtonNo9;
    private javax.swing.JButton ButtonNot;
    private javax.swing.JButton ButtonOct;
    private javax.swing.JButton ButtonOr;
    private javax.swing.JButton ButtonPercentage;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JButton ButtonPlusMinus;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonXOr;
    private javax.swing.JTextField DecDisplay;
    private javax.swing.JTextField Display;
    private javax.swing.JTextField HexDisplay;
    private javax.swing.JTextField OctDisplay;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
