/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFirstCalculator;

/**
 *
 * @author a7med
 */
public class Scientific extends javax.swing.JFrame {

    double FirstNum;
    double SecondNum;
    double Result;
    String Operation;
    
    public Scientific() {
        setSize(735,445);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        Display = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();
        ButtonNo9 = new javax.swing.JButton();
        ButtonNo7 = new javax.swing.JButton();
        ButtonNo8 = new javax.swing.JButton();
        ButtonPercentage = new javax.swing.JButton();
        ButtonNo5 = new javax.swing.JButton();
        ButtonNo3 = new javax.swing.JButton();
        ButtonNo1 = new javax.swing.JButton();
        ButtonNo2 = new javax.swing.JButton();
        ButtonNo4 = new javax.swing.JButton();
        ButtonNo6 = new javax.swing.JButton();
        ButtonBackspace = new javax.swing.JButton();
        ButtonDecimalPoint = new javax.swing.JButton();
        ButtonPlusMinus = new javax.swing.JButton();
        ButtonNo0 = new javax.swing.JButton();
        ButtonMultiplicatioin = new javax.swing.JButton();
        ButtonDIvision = new javax.swing.JButton();
        ButtonPlus = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        ButtonCos = new javax.swing.JButton();
        ButtonTanInverse = new javax.swing.JButton();
        ButtonSinInverse = new javax.swing.JButton();
        ButtonCosInverse = new javax.swing.JButton();
        ButtonTan = new javax.swing.JButton();
        ButtonCosh = new javax.swing.JButton();
        ButtonSqrtOfX = new javax.swing.JButton();
        ButtonLog = new javax.swing.JButton();
        ButtonLn = new javax.swing.JButton();
        ButtonSinh = new javax.swing.JButton();
        ButtonTanh = new javax.swing.JButton();
        ButtonSin = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        ButtonAbsolute = new javax.swing.JButton();
        ButtonPi = new javax.swing.JButton();
        ButtonXSquare = new javax.swing.JButton();
        ButtonInverted = new javax.swing.JButton();
        ButtonXQupe = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        TitleLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(232, 155, 25));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Scientific Calculator");
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(50, 0, 620, 47);

        BackButton.setBackground(new java.awt.Color(95, 64, 59));
        BackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(201, 176, 168));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(10, 10, 73, 30);

        Display.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(Display);
        Display.setBounds(37, 53, 660, 82);

        ButtonReset.setBackground(new java.awt.Color(29, 76, 170));
        ButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        ButtonReset.setText("C");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonReset);
        ButtonReset.setBounds(130, 140, 70, 60);

        ButtonNo9.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo9.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo9.setText("9");
        ButtonNo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo9ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo9);
        ButtonNo9.setBounds(210, 200, 70, 60);

        ButtonNo7.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo7.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo7.setText("7");
        ButtonNo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo7);
        ButtonNo7.setBounds(50, 200, 70, 60);

        ButtonNo8.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo8.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo8.setText("8");
        ButtonNo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo8);
        ButtonNo8.setBounds(130, 200, 70, 60);

        ButtonPercentage.setBackground(new java.awt.Color(29, 76, 170));
        ButtonPercentage.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPercentage.setText("%");
        getContentPane().add(ButtonPercentage);
        ButtonPercentage.setBounds(210, 140, 70, 60);

        ButtonNo5.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo5.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo5.setText("5");
        ButtonNo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo5);
        ButtonNo5.setBounds(130, 260, 70, 60);

        ButtonNo3.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo3.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo3.setText("3");
        ButtonNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo3);
        ButtonNo3.setBounds(210, 320, 70, 60);

        ButtonNo1.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo1.setText("1");
        ButtonNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo1);
        ButtonNo1.setBounds(50, 320, 70, 60);

        ButtonNo2.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo2.setText("2");
        ButtonNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo2);
        ButtonNo2.setBounds(130, 320, 70, 60);

        ButtonNo4.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo4.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo4.setText("4");
        ButtonNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo4);
        ButtonNo4.setBounds(50, 260, 70, 60);

        ButtonNo6.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo6.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo6.setText("6");
        ButtonNo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo6);
        ButtonNo6.setBounds(210, 260, 70, 60);

        ButtonBackspace.setBackground(new java.awt.Color(29, 76, 170));
        ButtonBackspace.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBackspace.setText("←");
        ButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBackspace);
        ButtonBackspace.setBounds(50, 140, 70, 60);

        ButtonDecimalPoint.setBackground(new java.awt.Color(29, 76, 170));
        ButtonDecimalPoint.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDecimalPoint.setText(".");
        ButtonDecimalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDecimalPointActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDecimalPoint);
        ButtonDecimalPoint.setBounds(210, 380, 70, 60);

        ButtonPlusMinus.setBackground(new java.awt.Color(29, 76, 170));
        ButtonPlusMinus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPlusMinus.setText("+/-");
        ButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlusMinus);
        ButtonPlusMinus.setBounds(50, 380, 70, 60);

        ButtonNo0.setBackground(new java.awt.Color(70, 63, 58));
        ButtonNo0.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNo0.setText("0");
        ButtonNo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNo0ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNo0);
        ButtonNo0.setBounds(130, 380, 70, 60);

        ButtonMultiplicatioin.setBackground(new java.awt.Color(29, 76, 170));
        ButtonMultiplicatioin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMultiplicatioin.setText("×");
        ButtonMultiplicatioin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicatioinActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMultiplicatioin);
        ButtonMultiplicatioin.setBounds(290, 200, 70, 60);

        ButtonDIvision.setBackground(new java.awt.Color(29, 76, 170));
        ButtonDIvision.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDIvision.setText("÷");
        ButtonDIvision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDIvisionActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDIvision);
        ButtonDIvision.setBounds(290, 140, 70, 60);

        ButtonPlus.setBackground(new java.awt.Color(29, 76, 170));
        ButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPlus.setText("+");
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlus);
        ButtonPlus.setBounds(290, 320, 70, 60);

        ButtonMinus.setBackground(new java.awt.Color(29, 76, 170));
        ButtonMinus.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMinus.setText("-");
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMinus);
        ButtonMinus.setBounds(290, 260, 70, 60);

        ButtonEqual.setBackground(new java.awt.Color(29, 76, 170));
        ButtonEqual.setForeground(new java.awt.Color(153, 153, 153));
        ButtonEqual.setText("=");
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEqual);
        ButtonEqual.setBounds(290, 380, 70, 60);

        ButtonCos.setBackground(new java.awt.Color(167, 86, 0));
        ButtonCos.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCos.setText("cos");
        ButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCosActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCos);
        ButtonCos.setBounds(450, 140, 70, 60);

        ButtonTanInverse.setBackground(new java.awt.Color(167, 86, 0));
        ButtonTanInverse.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTanInverse.setText("tan-1");
        ButtonTanInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTanInverseActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTanInverse);
        ButtonTanInverse.setBounds(530, 200, 70, 60);

        ButtonSinInverse.setBackground(new java.awt.Color(167, 86, 0));
        ButtonSinInverse.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSinInverse.setText("sin-1");
        ButtonSinInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSinInverseActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSinInverse);
        ButtonSinInverse.setBounds(370, 200, 70, 60);

        ButtonCosInverse.setBackground(new java.awt.Color(167, 86, 0));
        ButtonCosInverse.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCosInverse.setText(" cos-1");
        ButtonCosInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCosInverseActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCosInverse);
        ButtonCosInverse.setBounds(450, 200, 70, 60);

        ButtonTan.setBackground(new java.awt.Color(167, 86, 0));
        ButtonTan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTan.setText("tan");
        ButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTanActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTan);
        ButtonTan.setBounds(530, 140, 70, 60);

        ButtonCosh.setBackground(new java.awt.Color(167, 86, 0));
        ButtonCosh.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCosh.setText("cosh");
        ButtonCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCoshActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCosh);
        ButtonCosh.setBounds(450, 260, 70, 60);

        ButtonSqrtOfX.setBackground(new java.awt.Color(29, 172, 170));
        ButtonSqrtOfX.setForeground(new java.awt.Color(0, 0, 0));
        ButtonSqrtOfX.setText("√x");
        ButtonSqrtOfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSqrtOfXActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSqrtOfX);
        ButtonSqrtOfX.setBounds(530, 320, 70, 60);

        ButtonLog.setBackground(new java.awt.Color(29, 172, 170));
        ButtonLog.setForeground(new java.awt.Color(0, 0, 0));
        ButtonLog.setText("log");
        ButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLog);
        ButtonLog.setBounds(370, 320, 70, 60);

        ButtonLn.setBackground(new java.awt.Color(29, 172, 170));
        ButtonLn.setForeground(new java.awt.Color(0, 0, 0));
        ButtonLn.setText("ln");
        ButtonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLnActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLn);
        ButtonLn.setBounds(450, 320, 70, 60);

        ButtonSinh.setBackground(new java.awt.Color(167, 86, 0));
        ButtonSinh.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSinh.setText("sinh");
        ButtonSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSinhActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSinh);
        ButtonSinh.setBounds(370, 260, 70, 60);

        ButtonTanh.setBackground(new java.awt.Color(167, 86, 0));
        ButtonTanh.setForeground(new java.awt.Color(255, 255, 255));
        ButtonTanh.setText("tanh");
        ButtonTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTanhActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTanh);
        ButtonTanh.setBounds(530, 260, 70, 60);

        ButtonSin.setBackground(new java.awt.Color(167, 86, 0));
        ButtonSin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSin.setText("sin");
        ButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSinActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSin);
        ButtonSin.setBounds(370, 140, 70, 60);

        ButtonE.setBackground(new java.awt.Color(29, 172, 170));
        ButtonE.setForeground(new java.awt.Color(0, 0, 0));
        ButtonE.setText("e");
        ButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonE);
        ButtonE.setBounds(370, 380, 70, 60);

        ButtonAbsolute.setBackground(new java.awt.Color(29, 172, 170));
        ButtonAbsolute.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAbsolute.setText("|x|");
        ButtonAbsolute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAbsoluteActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAbsolute);
        ButtonAbsolute.setBounds(610, 200, 70, 60);

        ButtonPi.setBackground(new java.awt.Color(29, 172, 170));
        ButtonPi.setForeground(new java.awt.Color(0, 0, 0));
        ButtonPi.setText("π");
        ButtonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPiActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPi);
        ButtonPi.setBounds(610, 140, 70, 60);

        ButtonXSquare.setBackground(new java.awt.Color(29, 172, 170));
        ButtonXSquare.setForeground(new java.awt.Color(0, 0, 0));
        ButtonXSquare.setText("x²");
        ButtonXSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXSquareActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonXSquare);
        ButtonXSquare.setBounds(610, 320, 70, 60);

        ButtonInverted.setBackground(new java.awt.Color(29, 172, 170));
        ButtonInverted.setForeground(new java.awt.Color(0, 0, 0));
        ButtonInverted.setText("1/x");
        ButtonInverted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInvertedActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonInverted);
        ButtonInverted.setBounds(610, 260, 70, 60);

        ButtonXQupe.setBackground(new java.awt.Color(29, 172, 170));
        ButtonXQupe.setForeground(new java.awt.Color(0, 0, 0));
        ButtonXQupe.setText("x³");
        ButtonXQupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXQupeActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonXQupe);
        ButtonXQupe.setBounds(610, 380, 70, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFirstCalculator/BlackWoodBackground.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 740, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Start().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setSize(755, 488);
    }//GEN-LAST:event_formWindowActivated

    private void ButtonNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo4ActionPerformed
        String Number = Display.getText() + ButtonNo4.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo4ActionPerformed

    private void ButtonNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo1ActionPerformed
        String Number = Display.getText() + ButtonNo1.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo1ActionPerformed

    private void ButtonNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo2ActionPerformed
        String Number = Display.getText() + ButtonNo2.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo2ActionPerformed

    private void ButtonNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo3ActionPerformed
        String Number = Display.getText() + ButtonNo3.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo3ActionPerformed

    private void ButtonNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo5ActionPerformed
        String Number = Display.getText() + ButtonNo5.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo5ActionPerformed

    private void ButtonNo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo6ActionPerformed
        String Number = Display.getText() + ButtonNo6.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo6ActionPerformed

    private void ButtonNo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo7ActionPerformed
        String Number = Display.getText() + ButtonNo7.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo7ActionPerformed

    private void ButtonNo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo8ActionPerformed
        String Number = Display.getText() + ButtonNo8.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo8ActionPerformed

    private void ButtonNo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo9ActionPerformed
        String Number = Display.getText() + ButtonNo9.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo9ActionPerformed

    private void ButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusMinusActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Number * (-1) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonPlusMinusActionPerformed

    private void ButtonDecimalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDecimalPointActionPerformed
        if (!Display.getText().contains(".")){
            Display.setText(Display.getText() + ButtonDecimalPoint.getText());
        }
    }//GEN-LAST:event_ButtonDecimalPointActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        String Result;
        SecondNum =Double.parseDouble(Display.getText());
        if (Operation == "+"){
            this.Result = FirstNum + SecondNum;
            Result=String.format("%.9f",this.Result);
            Display.setText(Result);
        }
        else if (Operation == "-"){
            this.Result = FirstNum - SecondNum;
            Result=String.format("%.9f",this.Result);
            Display.setText(Result);
        }
        else if (Operation == "*"){
            this.Result = FirstNum * SecondNum;
            Result=String.format("%.9f",this.Result);
            Display.setText(Result);
        }
        else if (Operation == "/"){
            this.Result = FirstNum / SecondNum;
            Result=String.format("%.9f",this.Result);
            Display.setText(Result);
        }
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void ButtonNo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNo0ActionPerformed
        String Number = Display.getText() + ButtonNo0.getText();
        Display.setText(Number);
    }//GEN-LAST:event_ButtonNo0ActionPerformed

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        FirstNum =Double.parseDouble(Display.getText());
        Display.setText(null);
        Operation=("+");
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        FirstNum =Double.parseDouble(Display.getText());
        Display.setText(null);
        Operation=("-");
    }//GEN-LAST:event_ButtonMinusActionPerformed

    private void ButtonMultiplicatioinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicatioinActionPerformed
        FirstNum =Double.parseDouble(Display.getText());
        Display.setText(null);
        Operation=("*");
    }//GEN-LAST:event_ButtonMultiplicatioinActionPerformed

    private void ButtonDIvisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDIvisionActionPerformed
        FirstNum =Double.parseDouble(Display.getText());
        Display.setText(null);
        Operation=("/");
    }//GEN-LAST:event_ButtonDIvisionActionPerformed

    private void ButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackspaceActionPerformed
        String Backspace = null;
        if (Display.getText().length() > 0){
            StringBuilder strB = new StringBuilder(Display.getText());
            strB.deleteCharAt(Display.getText().length() -1);
            Backspace = strB.toString();
            Display.setText(Backspace);
        }
    }//GEN-LAST:event_ButtonBackspaceActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        Display.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCosActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.cos(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonCosActionPerformed

    private void ButtonTanInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTanInverseActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.atan(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonTanInverseActionPerformed

    private void ButtonSinInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSinInverseActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.asin(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonSinInverseActionPerformed

    private void ButtonCosInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCosInverseActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.acos(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonCosInverseActionPerformed

    private void ButtonCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCoshActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.cosh(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonCoshActionPerformed

    private void ButtonSqrtOfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSqrtOfXActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.sqrt(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonSqrtOfXActionPerformed

    private void ButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.log(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonLogActionPerformed

    private void ButtonLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLnActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = (-Math.log(1-Number))/Number ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonLnActionPerformed

    private void ButtonSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSinhActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.sinh(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonSinhActionPerformed

    private void ButtonTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTanhActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.tanh(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonTanhActionPerformed

    private void ButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSinActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.sin(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonSinActionPerformed

    private void ButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEActionPerformed
        double Number = 2.71828182846;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonEActionPerformed

    private void ButtonAbsoluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAbsoluteActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        if (Number<0){
            Number=-Number;
        }
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonAbsoluteActionPerformed

    private void ButtonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPiActionPerformed
        Double Number = Math.PI ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonPiActionPerformed

    private void ButtonXSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXSquareActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.pow(Number,2) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonXSquareActionPerformed

    private void ButtonInvertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInvertedActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Display.setText(String.valueOf(1/Number));
    }//GEN-LAST:event_ButtonInvertedActionPerformed

    private void ButtonXQupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXQupeActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.pow(Number,3) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonXQupeActionPerformed

    private void ButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTanActionPerformed
        double Number = Double.parseDouble(String.valueOf(Display.getText()));
        Number = Math.tan(Number) ;
        Display.setText(String.valueOf(Number));
    }//GEN-LAST:event_ButtonTanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton ButtonAbsolute;
    private javax.swing.JButton ButtonBackspace;
    private javax.swing.JButton ButtonCos;
    private javax.swing.JButton ButtonCosInverse;
    private javax.swing.JButton ButtonCosh;
    private javax.swing.JButton ButtonDIvision;
    private javax.swing.JButton ButtonDecimalPoint;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonInverted;
    private javax.swing.JButton ButtonLn;
    private javax.swing.JButton ButtonLog;
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonMultiplicatioin;
    private javax.swing.JButton ButtonNo0;
    private javax.swing.JButton ButtonNo1;
    private javax.swing.JButton ButtonNo2;
    private javax.swing.JButton ButtonNo3;
    private javax.swing.JButton ButtonNo4;
    private javax.swing.JButton ButtonNo5;
    private javax.swing.JButton ButtonNo6;
    private javax.swing.JButton ButtonNo7;
    private javax.swing.JButton ButtonNo8;
    private javax.swing.JButton ButtonNo9;
    private javax.swing.JButton ButtonPercentage;
    private javax.swing.JButton ButtonPi;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JButton ButtonPlusMinus;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSin;
    private javax.swing.JButton ButtonSinInverse;
    private javax.swing.JButton ButtonSinh;
    private javax.swing.JButton ButtonSqrtOfX;
    private javax.swing.JButton ButtonTan;
    private javax.swing.JButton ButtonTanInverse;
    private javax.swing.JButton ButtonTanh;
    private javax.swing.JButton ButtonXQupe;
    private javax.swing.JButton ButtonXSquare;
    private javax.swing.JTextField Display;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
