/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFirstCalculator;

/**
 *
 * @author a7med
 */
public class Start extends javax.swing.JFrame {

    
    
    public Start() {
        setSize(735,445);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        Standard = new javax.swing.JButton();
        Scientific = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Programmer = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        TitleLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(232, 155, 25));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Choose Calculator");
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(0, 41, 735, 68);

        Standard.setBackground(new java.awt.Color(95, 64, 59));
        Standard.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Standard.setForeground(new java.awt.Color(201, 176, 168));
        Standard.setText("Standard");
        Standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardActionPerformed(evt);
            }
        });
        getContentPane().add(Standard);
        Standard.setBounds(265, 187, 195, 42);

        Scientific.setBackground(new java.awt.Color(95, 64, 59));
        Scientific.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Scientific.setForeground(new java.awt.Color(201, 176, 168));
        Scientific.setText("Scientific");
        Scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScientificActionPerformed(evt);
            }
        });
        getContentPane().add(Scientific);
        Scientific.setBounds(265, 241, 195, 42);

        BackButton.setBackground(new java.awt.Color(95, 64, 59));
        BackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(201, 176, 168));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(30, 20, 110, 42);

        Programmer.setBackground(new java.awt.Color(95, 64, 59));
        Programmer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Programmer.setForeground(new java.awt.Color(201, 176, 168));
        Programmer.setText("Programmer");
        Programmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgrammerActionPerformed(evt);
            }
        });
        getContentPane().add(Programmer);
        Programmer.setBounds(265, 295, 195, 42);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFirstCalculator/BlackWoodBackground.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, -10, 740, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardActionPerformed
        new Standard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StandardActionPerformed

    private void ScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScientificActionPerformed
        new Scientific().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ScientificActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new StartPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setSize(755, 488);
    }//GEN-LAST:event_formWindowActivated

    private void ProgrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgrammerActionPerformed
        new Programmer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProgrammerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Programmer;
    private javax.swing.JButton Scientific;
    private javax.swing.JButton Standard;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
