/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFirstCalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author a7med
 */
public class StartPage extends javax.swing.JFrame {

    
    
    public StartPage() {
        setSize(735,445);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        Copyrights = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 155, 25));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All in One Calculator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 41, 735, 68);

        StartButton.setBackground(new java.awt.Color(95, 64, 59));
        StartButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StartButton.setForeground(new java.awt.Color(201, 176, 168));
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartButton);
        StartButton.setBounds(265, 187, 195, 42);

        AboutButton.setBackground(new java.awt.Color(95, 64, 59));
        AboutButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AboutButton.setForeground(new java.awt.Color(201, 176, 168));
        AboutButton.setText("About");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AboutButton);
        AboutButton.setBounds(265, 241, 195, 42);

        ExitButton.setBackground(new java.awt.Color(95, 64, 59));
        ExitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(201, 176, 168));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(265, 295, 195, 42);

        Copyrights.setForeground(new java.awt.Color(252, 250, 241));
        Copyrights.setText("©2020 - Ahmed Ebrahim Almalali - 20197531 - Software Engineering");
        getContentPane().add(Copyrights);
        Copyrights.setBounds(14, 423, 383, 16);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFirstCalculator/BlackWoodBackground.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 740, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        new Start().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StartButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        JOptionPane.showMessageDialog(AboutButton, "Programming by Ahmed Ebrahim Using Java\nIT Training Group");
    }//GEN-LAST:event_AboutButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to exit the program?", "Exit Program Message Box",JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
        dispose();
        }
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setSize(755, 488);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Copyrights;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
